name: Publish GUI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish_gui:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Debug, Release]
        bundled: [true, false]
        singlefile: [true]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build UndertaleModTool --no-restore
      #  dotnet build UndertaleModToolUpdater --no-restore
    - name: Publish ${{ matrix.os }} GUI
      run: |
        dotnet publish UndertaleModTool -c ${{ matrix.configuration }} -r win-x64 --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=${{ matrix.singlefile }} --output ${{ matrix.os }}
      #  dotnet publish UndertaleModToolUpdater -c ${{ matrix.configuration }} -r win-x64 --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=false --output ${{ matrix.os }}/Updater
    - name: Copy external files
      run: |
        cp ./README.md ./${{ matrix.os }}
        cp ./SCRIPTS.md ./${{ matrix.os }}
        cp ./LICENSE.txt ./${{ matrix.os }}
        cp ./.disable_gb1click ./${{ matrix.os }}
    - name: Upload ${{ matrix.os }} GUI
      uses: actions/upload-artifact@v4
      with:
        name: UTMTCE-GUI64BIT-${{ matrix.os }}-${{ matrix.configuration }}-isBundled-${{ matrix.bundled }}-isSingleFile-${{ matrix.singlefile }}
        path: ${{ matrix.os }}
